### ISSUE TITLE
Add A3I5 support

### ISSUE THREAD

**Issue by NoneGiven** [hackyourlife/metroidprimehunters#1]
Contrary to this ancient code comment from dsgraph...

```
/*
	Texture formats:

		0 = 2bit palettised
		1 = 4bit palettised
		2 = 8bit palettised
		4 = 8bit greyscale
		5 = 16bit RGBA

	There may be more, but these are the only ones used by Metroid

	Palette entries are 16bit RGBA
*/
```

texture format ID = 6 is also used by MPH. It is the NDS A3I5 format. I learned this from this [Google Doc](https://docs.google.com/spreadsheets/d/1EqpTOhYvnbpBHiL24jBsh320VIXssrsc7FhXCDMTDpU/edit#gid=67743607) and verified with a few of the small handful of models that use it. Should be trivial to implement this as a slight adjustment to the bit twiddling already implemented for A5I3.

**Comment by hackyourlife** [comment]
This is correct and I'll merge your PR, but I had that fix/change in a private fork for a long time already; if you're interested in the "up to date" project, look at this repository: https://github.com/hackyourlife/mph-viewer

The goal of that project is to integrate all pieces in one project, with proper support for entities / scan logs / …
I didn't upload it for a long time because it's still incomplete and you need to unpack all the .arc files for that new version to work. But if you want to play around with levels from Hunters, that's definitely the code you want to look at. To get started, create a `data` folder in the same folder as `dsgraph.exe`, extract the game's romfs into that data folder, and extract all the `.arc` files in `archives/` (e.g. `archives/e3Level.arc` to `archives/datae3Level/`). Then launch the program with `dsgraph 95` to view the multiplayer map "Proving Grounds". `95` is the internal ID of that room.

There are still lots of open problems like transparency glitches with entities, missing implementations of entities (e.g. enemy spawners / "objects" / …), missing/incorrect behavior of existing entities (e.g. position computation of jump pads), missing animations (color/UV/bone), missing collision geometry / portals / … but I think those things are way more interesting than fixing bugs in *this* project which were already fixed there.

**Comment by NoneGiven** [comment]
Thanks, I'll definitely check it out. I'm most interested in bone animations for the models, but everything else in there is awesome too. If I have anything to contribute I'll try to help out, though it looks like you're way ahead of me with the stuff in that branch.
